language: node_js
matrix:
  include:
  - name: "Node.js 12"
    node_js: "12"
  - name: "Node.js 11"
    node_js: "11"
  - name: "Node.js 10"
    node_js: "10"
  - name: "Node.js 6"
    node_js: "9"
  - name: "Node.js 6"
    node_js: "8"
  - name: "Node.js 6"
    node_js: "7"
  - name: "Node.js 6"
    node_js: "6"
  - name: "Node.js 5"
    node_js: "5"
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
      - export PATH="$HOME/.yarn/bin:$PATH"
  - name: "Node.js 4"
    node_js: "4"
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
      - export PATH="$HOME/.yarn/bin:$PATH"